#!/bin/bash
# pl_fs_vol2mgh
#
# Assigns values from a volume to FreeSufer surafce vertex. 
#
#-----------------------------------------------------------------------------
# Inputs
#-----------------------------------------------------------------------------
# $1 - Subject IDs
# $2 - Subfolders (where nii are stored) 
# $3 - nii file name suffixes
# $4 - nii file name stem 
# $5 - FWHM
#-----------------------------------------------------------------------------
# Outputs
#-----------------------------------------------------------------------------
# xx.mgh - FreeSurfer mgh surface file 
# ----------------------------------------------------------------------------
# Usage:
#   sh fs_vol2mgh.sh "Subject IDs" "subfolders" "nii file name suffix"
#   "nii file name stem" "FWHM"
#-----------------------------------------------------------------------------
# Note: This script uses a cortical sampling step of 0.5. Adjust as desired. 
# You will need to first create a register.dat file.
#-----------------------------------------------------------------------------
# Source: Original was generated by DSS
# 
# 26/12/2020: Generated (SS)
# 25/01/2022: Last modified (PL)

#-----------------------------------------------------------------------------Define variables 

SubjIDs=$1
SubFlds=$2
FileNameSuffixes=$3
FileNameStem=$4
FWHM=$5

#-----------------------------------------------------------------------------Loop through subject IDs

for i_subj in $SubjIDs
do

    #-------------------------------------------------------------------------Loop through subfolders

    for i_subfld in $SubFlds
    do

    PathSubFld=$SUBJECTS_DIR/$i_subj/$i_subfld
    cd $PathSubFld

        #---------------------------------------------------------------------Loop through file names

        for i_fname in $FileNameSuffixes
        do

        #---------------------------------------------------------------------Surface projection
        
        echo "Converting $i_fname (subject: $i_subj | subfolder: $i_subfld)"
        # Left hemisphere 
        mri_vol2surf --mov $FileNameStem$i_fname.nii --reg register.dat \
        --hemi lh --o ./lh_$FileNameStem$i_fname.mgh --projfrac-avg 0 0.8 0.1 --surf-fwhm $FWHM
        # Right hemisphere 
        mri_vol2surf --mov $FileNameStem$i_fname.nii --reg register.dat \
        --hemi rh --o ./rh_$FileNameStem$i_fname.mgh --projfrac-avg 0 0.8 0.1 --surf-fwhm $FWHM
        done

    done

done