#!/bin/bash
# ss_fs_regdat
#
# Creates FreeSurfer registration file.
#
#-----------------------------------------------------------------------------
# Inputs
#-----------------------------------------------------------------------------
# $1 - Subject ids [separated by spaces] 
# $2 - Subfolders (where nii are stored) [separated by spaces]
# $3 - nii file name
#-----------------------------------------------------------------------------
# Outputs
#-----------------------------------------------------------------------------
# register.dat - registration file [functional data to FreeSurfer mesh] 
# ----------------------------------------------------------------------------
# Usage:
#   sh ss_fs_regdat.sh "subject IDs" "subfolders" "nii file without extension" 
#-----------------------------------------------------------------------------
# Source: Original was generated by DSS
#
# 26/12/2020: Generated (SS)
# 07/01/2020: Last modified (SS)

#-----------------------------------------------------------------------------Define variables 

SubjIDs=$1
SubFlds=$2
FileName=$3

#-----------------------------------------------------------------------------Loop through subject IDs

for i_subj in $SubjIDs
do

#-----------------------------------------------------------------------------Loop through subfolders

    for i_subfld in $SubFlds
    do

    #-------------------------------------------------------------------------Change to subfolder
    
    PathSubFld=$SUBJECTS_DIR/$i_subj/$i_subfld
    cd $PathSubFld

    #-------------------------------------------------------------------------Create registration file 

    tkregister2 --mov $FileName.nii --s $i_subj --regheader --noedit --reg register.dat

    done
done
